# Sample workflow for building, processing, and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with Preprocessing

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y sass
          npm install -g terser clean-css-cli html-minifier-terser

      - name: Convert Sass to CSS
        run: |
          sass styles/main.scss styles/main.css --style=compressed
          rm styles/main.scss

      - name: Minify CSS
        run: cleancss -o styles/main.min.css styles/main.css

      - name: Uglify JavaScript
        run: terser scripts/main.js -o scripts/main.min.js --compress --mangle

      - name: Minify HTML
        run: |
          html-minifier-terser --collapse-whitespace --remove-comments --minify-css true --minify-js true -o index.min.html index.html
          mv index.min.html index.html

      - name: Update HTML links
        run: |
          sed -i 's/main.css/main.min.css/g' index.html
          sed -i 's/main.js/main.min.js/g' index.html

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload Processed Files
        uses: actions/upload-pages-artifact@v3

  # Deployment job
  deploy:
    environment:
      name: page-builder
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
